### ISSUE TITLE
terraform debug logs (opt-in or retry-with-log-on-failure)

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/terraform-release#12]
## expected behavior

As a terraform-release user
* in order to diagnose crashes or error of terraform providers
* I need to be able to access [terraform debugging logs](https://www.terraform.io/docs/internals/debugging.html) controlled by [TF_LOG](https://www.terraform.io/docs/commands/environment-variables.html) env var
* and I need to turn on provider specific debug logs through env such as potentially [cloudfoundry-community/terraform-provider-cloudfoundry](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/5c9b3c1ea9db028719eabc4ddfea978df570d6e0/README.md), see https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/issues/197
> You can export the following environment variables to enable detail debug logs.
> export CF_DEBUG=true
> export CF_TRACE=debug.log

## observed bevahior

No way to configure tf logs

### env var

Add a new property to declare additional enviromnent variables set before execution terraform binary

```yaml
  terraform.env_vars:
    description:
      map of environment variables to declare prior to execute the job
   example:
     - TF_LOG: trace
     - CF_DEBUG: true
     - CF_TRACE: true
```

Note that the following yaml block is valid against YAML specs
- validated in the following validators
   - https://jsonformatter.org/yaml-validator
   - https://onlineyamltools.com/validate-yaml
   - http://www.yamllint.com/ (which reformats the later map using the [ a complex mapping key](https://yaml.org/spec/1.2/spec.html#id2760395) in which key can be a non scalar such as an array or a mapping.
- any quoted characters can be used when quoted, see https://stackoverflow.com/questions/9065136/allowed-characters-in-map-key-identifier-in-yaml

### retry on failure with verbose mode

* Add optin to automatically retry on failures and declare specific env vars in this mode

```yaml
  terraform.retry_on_failure_and_set_env_vars:
    description:
      map of environment variables to declare prior to retry a failed job execution
   example:
     - TF_LOG: trace
     - CF_DEBUG: true
     - CF_TRACE: true
```
