### ISSUE TITLE
Support for modules and named tf spec files

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/terraform-release#8]
## expected behavior

As a terraform-release user
* in order to apply custom modules
* I need to be able to specify terraform modules that are expected to be in directories

https://www.terraform.io/docs/modules/index.html#module-structure
> To define a module, create a new directory for it and place one or more .tf files inside just as you would do for a root module. Terraform can load modules either from local relative paths or from remote repositories;

## observed bevahior

https://github.com/orange-cloudfoundry/terraform-release/blob/e75d64824d98ec83601afa01ebc3d74914733aa0/jobs/terraform-apply/spec#L23-L25

## Possible improvement

```yaml
  terraform.specs:
    description:
      map of inline terraform configuration to apply keyed by relative file path
   example:
     - flat-config.tf: "inlined-tf-config content"
     - module/config.tf: "inlined-tf-config content"
     - module/submodule/config.tf: "inlined-tf-config content"
     - "if ever needed config file name with special characters such as : ! # chars.tf": "inlined-tf-config content"
```

Note that the following yaml block is valid against YAML specs
- validated in the following validators
   - https://jsonformatter.org/yaml-validator
   - https://onlineyamltools.com/validate-yaml
   - http://www.yamllint.com/ (which reformats the later map using the [ a complex mapping key](https://yaml.org/spec/1.2/spec.html#id2760395) in which key can be a non scalar such as an array or a mapping.
- any quoted characters can be used when quoted, see https://stackoverflow.com/questions/9065136/allowed-characters-in-map-key-identifier-in-yaml
